name: publish

on:
  release:
    types: [published, edited]

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org

      - name: NPM Publish
        run: |
          if [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
